module.exports = {
  db: "ehboxmetrics3",
  measurement: "oracle",
  top: 10,
  alerts: [
    // TOTAL COUNT
    {
      type: "averageAnomalyOnIncrease",
      name: "Total message count increase",
      metric: "messageCount.total",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total message count decrease",
      metric: "messageCount.total",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages deleted increase",
      metric: "messageCount.byStatus.22",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages deleted decrease",
      metric: "messageCount.byStatus.22",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages standby increase",
      metric: "messageCount.byStatus.99",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages standby decrease",
      metric: "messageCount.byStatus.99",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages binned increase",
      metric: "messageCount.byStatus.21",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages binned decrease",
      metric: "messageCount.byStatus.21",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages with mimetype text larger than 2mb increase",
      metric: "messageCount.withMimeTypeLikeTextAndSizeOver2Mb",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages with mimetype text larger than 2mb decrease",
      metric: "messageCount.withMimeTypeLikeTextAndSizeOver2Mb",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total unread messages increase",
      metric: "messageCount.unRead",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total unread messages decrease",
      metric: "messageCount.unRead",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total read messages increase",
      metric: "messageCount.read",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total read messages decrease",
      metric: "messageCount.read",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },
    // TOTAL SIZE
    {
      type: "averageAnomalyOnIncrease",
      name: "Total message size increase",
      metric: "messageSize.total",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total message size decrease",
      metric: "messageSize.total",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages deleted size increase",
      metric: "messageSize.byStatus.22",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages deleted size decrease",
      metric: "messageSize.byStatus.22",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages standby size increase",
      metric: "messageSize.byStatus.99",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages standby size decrease",
      metric: "messageSize.byStatus.99",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages binned size increase",
      metric: "messageSize.byStatus.21",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages binned size decrease",
      metric: "messageSize.byStatus.21",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total messages with mimetype text larger than 2mb size increase",
      metric: "messageSize.withMimeTypeLikeTextAndSizeOver2Mb",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total messages with mimetype text larger than 2mb size decrease",
      metric: "messageSize.withMimeTypeLikeTextAndSizeOver2Mb",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total unread messages size increase",
      metric: "messageSize.unRead",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total unread messages size decrease",
      metric: "messageSize.unRead",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnIncrease",
      name: "Total read messages size increase",
      metric: "messageSize.read",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "averageAnomalyOnDecrease",
      name: "Total read messages size decrease",
      metric: "messageSize.read",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },
    // TOP BOX COUNT
    {
      type: "topBoxes",
      name: "Message count increase for box",
      metric: "messageCountTop.all",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    },{
      type: "topBoxes",
      name: "Deleted message count increase for box",
      metric: "messageCountTop.byStatus.22",
      startSample1: "30d",
      stopSample1: "",
      groupSample1: "",
      startSample2: "3d",
      stopSample2: "",
      groupSample2: "72h",
      warnThresholdMultiplicator: "0.50",
      critThresholdMultiplicator: "0.75"
    }
  ]
}


// {
//   type: "topBoxes",
//   name: "Box messages mimetype text larger than 2mb increase",
//   metric: "messageCountTop.withMimeTypeLikeTextAndSizeOver2Mb",
//   startSample1: "30d",
//   stopSample1: "",
//   groupSample1: "",
//   startSample2: "3d",
//   stopSample2: "",
//   groupSample2: "72h",
//   critThresholdMultiplicator: "0.75"
// }
